---
- set_fact:
    opm_path: /usr/share/openstack-puppet-modules-git

- name: clone OPM repo
  git:
    repo={{ opm_git_repo }}
    dest={{ opm_path }}
    recursive=no

- name: switch OPM to correct ref
  shell: /usr/bin/git checkout -f {{ opm_git_ref }}
  args:
    chdir: "{{ opm_path }}"

- name: update submodules if necessary
  shell: /usr/bin/git submodule update --init
  args:
    chdir: "{{ opm_path }}"
