---
- name: run puppet with neutron compute classes
  shell: /usr/bin/puppet apply -v -d --modulepath={{ opm_path }}/:{{ quickstack_modules_path }}/ -e "hiera_include('compute_classes')" &> /tmp/puppet-apply.log
  async: 9200
  poll: 30
